"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Nav";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [mode, setMode] = useState("");

  //Callback function to handle data passed from the child
  const handleDataFromChild = (data: any) => {
    setMode(data);
  };

  return (
    <html lang="en" className={mode}>
      <body className={`${inter.className} bg-[#FAFAFA] dark:bg-[#202C36]`}>
        <Navbar onData={handleDataFromChild} />
        {children}
      </body>
    </html>
  );
}
